type PosixSignal* {.pure.} = enum
  Signal0   =  0,
  SIGHUP    =  1, # terminal line hangup
  SIGINT    =  2, # interrupt program
  SIGQUIT   =  3, # quit program
  SIGILL    =  4, # illegal instruction
  SIGTRAP   =  5, # trace trap
  SIGABRT   =  6, # abort program (formerly SIGIOT)
  SIGEMT    =  7, # emulate instruction executed
  SIGFPE    =  8, # floating-point exception
  SIGKILL   =  9, # kill program
  SIGBUS    = 10, # bus error
  SIGSEGV   = 11, # segmentation violation
  SIGSYS    = 12, # non-existent system call invoked
  SIGPIPE   = 13, # write on a pipe with no reader
  SIGALRM   = 14, # real-time timer expired
  SIGTERM   = 15, # software termination signal
  SIGURG    = 16, # urgent condition present on socket
  SIGSTOP   = 17, # stop (cannot be caught or ignored)
  SIGTSTP   = 18, # stop signal generated from keyboard
  SIGCONT   = 19, # continue after stop
  SIGCHLD   = 20, # child status has changed
  SIGTTIN   = 21, # background read attempted from control terminal
  SIGTTOU   = 22, # background write attempted to control terminal
  SIGIO     = 23, # I/O is possible on a descriptor (see fcntl(2))
  SIGXCPU   = 24, # cpu time limit exceeded (see setrlimit(2))
  SIGXFSZ   = 25, # file size limit exceeded (see setrlimit(2))
  SIGVTALRM = 26, # virtual time alarm (see setitimer(2))
  SIGPROF   = 27, # profiling timer alarm (see setitimer(2))
  SIGWINCH  = 28, # Window size change
  SIGINFO   = 29, # status request from keyboard
  SIGUSR1   = 30, # User defined signal 1
  SIGUSR2   = 31, # User defined signal 2
